language: python

python: "3.6"

cache: pip

jobs:
  include:
    - stage: test
      language: python
      cache: pip
      python: "3.6"
      install: pip install .
      script: pytest

    - stage: test
      language: python
      # Python 3.7 still not available in usual distro
      sudo: required
      dist: xenial
      python: "3.7"
      install:
        - pip install .
      script: pytest

    - stage: deploy to pypi
      if: tag IS present
      script: skip
      deploy:
        - provider: pypi
          distributions: "sdist bdist_wheel"
          username: $PYPI_USERNAME
          password: $PYPI_PASSWORD
          on:
            tags: true
